### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by chengyh23** [callum-rhodes/gabp_mapping#2]
TabError

```
Traceback (most recent call last):
  File "/home/nuci7/gabp/devel/lib/gabp_mapping/main_2D.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/nuci7/gabp/src/gabp_mapping/scripts/main_2D.py", line 113
    rospy.on_shutdown(GaBP_k.on_shutdown)
                                        ^
TabError: inconsistent use of tabs and spaces in indentation
Traceback (most recent call last):
  File "/home/nuci7/gabp/devel/lib/gabp_mapping/throttlePID.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/nuci7/gabp/src/gabp_mapping/scripts/throttlePID.py", line 29
    if topic_type == 'Float32':
                              ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by chengyh23** [comment]
fixed and tested on this branch
https://github.com/chengyh23/gabp_mapping
